# WEBSITE METADATA
title: Chris Grieser
description: Researcher in sociology & software developer

#───────────────────────────────────────────────────────────────────────────────
# JEKYLL CONFIGURATION
# https://jekyllrb.com/docs/configuration/options/

# Builtin themes for GitHub Pages: https://pages.github.com/themes/
# theme: jekyll-theme-modernist

# Remote themes, allowing any Jekyll theme: https://jekyllrb.com/docs/themes/
plugins: [jekyll-remote-theme]
remote_theme: mmistakes/minimal-mistakes@4.26.2
