# WEBSITE METADATA
title: Chris Grieser
description: Researcher in sociology & software developer

#───────────────────────────────────────────────────────────────────────────────
# JEKYLL CONFIGURATION
# https://jekyllrb.com/docs/configuration/options/

github: { is_project_page: false } # remove the "View on GitHub" button

#───────────────────────────────────────────────────────────────────────────────
# THEME

# Builtin themes for GitHub Pages: https://pages.github.com/themes/
theme: jekyll-theme-slate
# Remote allows more Jekyll theme: https://jekyllrb.com/docs/themes/
# plugins: [jekyll-remote-theme]
# remote_theme: …

