# Website metadata
title: Chris Grieser
description: Researcher in sociology & programmer

#───────────────────────────────────────────────────────────────────────────────

# Jekyll configuration
theme: jekyll-theme-minimal

# plugins: [jekyll-remote-theme]
# remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
