# Website metadata
title: Chris Grieser
description: Researcher in sociology & programmer

#───────────────────────────────────────────────────────────────────────────────

# Jekyll configuration

# available themes for GitHub Pages: https://pages.github.com/themes/
theme: jekyll-theme-modernist

# for themes not hosted at GitHub
# plugins: [jekyll-remote-theme]
# remote_theme: pages-themes/modernist@v0.2.0
